### ISSUE TITLE
[FEAT] 이용약관 관련

### ISSUE THREAD

**Issue by shon5544** [yourweather/yourweather-server#100]
## Description

> 이용 약관 처리는 서버에서 전달해주는 것으로 했었음. 한 가지 의견 들어온 건 우리 github repo wiki 에 이용 약관 적고 그 링크를 전달하는 거로 하는 게 어떨까하는 건데 자유롭게 의견 나눠주세용

## Progress

- [ ] 이용약관 기능 제공
- [ ] 테스트

**Comment by HI-JIN2** [comment]
좋습니다. 그냥 코드로 처리하지 않고  github repo wiki에서 처리해도 좋을 듯 해용! 위키 생성하도록 하겠습니다

**Comment by shon5544** [comment]
@HI-JIN2 @packdev937 해당 이슈는 프론트에서 wiki 링크를 제공하는 것으로 바뀌었습니다! 코드 처리는 필요하지 않을 것 같네용
