### ISSUE TITLE
[FIX] fix password changing api

### ISSUE THREAD

**Issue by shon5544** [yourweather/yourweather-server#111]
## Description

![image](https://github.com/yourweather/yourweather-server/assets/65557784/e1b808c3-07d8-41b7-a9ed-01f1446dbfa6)
> 비밀번호 변경 시 기존 비밀번호와 새 비밀번호를 받아야합니다. 받아서 기존 비밀번호가 일치하는 지 검사한 후, 맞다면 새 비밀번호로 update해주고 아니라면 Exception을 터트리거나 해야할 것 같습니다!

## Progress

- [x] 기존 request 폼 수정
- [x] 비밀번호가 일치하는 지 검사한 후 맞다면 새 비밀번호로 update 아니라면 Exception
- [x] 테스트

**Comment by HI-JIN2** [comment]
근데 보통 현재 비밀번호와 바꿀 비밀번호를 다른 화면에서 받지 않나요? 그러니까 화면1에서 비밀번호체크를 하고 맞으면 화면2로 넘어가서 비밀번호 변경을 하는 게 통상적일 것 같은데...

**Comment by packdev937** [comment]
> 근데 보통 현재 비밀번호와 바꿀 비밀번호를 다른 화면에서 받지 않나요? 그러니까 화면1에서 비밀번호체크를 하고 맞으면 화면2로 넘어가서 비밀번호 변경을 하는 게 통상적일 것 같은데...

네이버 같은 경우는 저렇게 한번에 받기도 하는거 같아요. 이거는 개발자의 취향에 따라 갈리는듯?

**Comment by shon5544** [comment]
이 부분은 프론트 팀과 한번 상의를 해봐야할 것 같네요,,!
일단, 개인적인 생각으론 새 UI를 만들 시간도 부족할 것 같으니 일단 우리는 지금 당장 주어진 UI에 대한 요구사항을 달성하는게 당장은 더 좋을 것 같네요
