### ISSUE TITLE
WeatherController create 관련 제의

### ISSUE THREAD

**Issue by shon5544** [yourweather/yourweather-server#47]
## Description

> WeatherController에 /create를 만든 이유가 있을까요? 

날씨와 메모는 같이 다루어집니다. 만약 메모를 작성하려고 하는데, 해당 일의 날씨 엔티티가 없다면? 
날씨 엔티티를 자동으로 만들어야 하는거죠.

메모 write 기능을 보면 해당 일에 날씨가 없으면 클라이언트에게 "해당 일에 날씨가 없다"라고 메세지를 보내요.
만약 우리 앱 GUI에서 해당 일의 날씨를 먼저 만들고, 그 다음에 메모를 추가하는 것이라면 맞는 상황이에요.

그렇지만 우리는 그런 것 없이 바로 메모를 만드니까, MemoController에서 /write를 할 때 자동으로 Weather가 있는지 검사하고, 없으면 Weather 엔티티를 생성해주는 쪽이 훨씬 자연스러워 보여요.

그렇기 때문에 WeatherController의 /write를 지우고, MemoController의 /write에 Weather가 없을 때의 분기를 만들어 주는 것이 좋아보입니다!

## etc
- Weather와 Memo의 네이밍에 개선이 필요해 보여요.
- Weather는 하루의 기록을 담당하는 하루의 기록집 같은 거고 Memo에서 오히려 날씨가 어떤지 결정하는 거니까, 차라리 Diary(구 Weather), Weather(구 Memo) 정도가 적당해 보이네요.
- Diary도 솔직히 말하면 좀 별로인데 같이 네이밍을 잘 선정해봅시다.

**Comment by HI-JIN2** [comment]
좋은 이슈입니다. 메인 이슈에 동의하고, 네이밍 관련해서는 생각을 열심히 해보겠습니다. 👍
