### ISSUE TITLE
[Test] Test with JUnit5

### ISSUE THREAD

**Issue by packdev937** [yourweather/yourweather-server#54]
## Description

> Postman을 이용해 API 테스트를 진행하려고 했으나, JWT Token 관련 이슈로 인해 테스트가 제대로 진행되지 않았습니다. 따라서 JUnit5 를 이용한 테스트코드를 작성해보려고 합니다. 

## Progress

- [ ] 각 Controller, Service에 대한 테스트 코드 작성
- [ ] Spring Rest Docs 연결 시도

**Comment by shon5544** [comment]
저희 Swagger 사용하기로 하지 않았나요? 이름이 헷갈릴 수 있는데, Swagger에는 springfox swagger와 springdoc swagger가 있습니다.! 그 중에서 저희는 springdoc을 사용하기로 한 것이구용 참고해주세요!

**Comment by shon5544** [comment]
또한 Postman에서의 jwt 관련 이슈는 jwt 토큰을 Postman에 어떻게 기록을 할 지 모르겠어서 그런 것일까요?
혹시 모르니 참고하시라고 어떻게 하는 지 기록해두겠습니다!

![image](https://github.com/yourweather/yourweather-server/assets/65557784/c5e1e7ab-a005-4a8d-a66b-0c285684119f)
> 작동 후 jwt 토큰을 돌려주는 signup 요청.
```javascript
pm.globals.set("access_token", pm.response.headers.get("Authorization"));
pm.globals.set("refresh_token", pm.response.headers.get("Authorization-refresh"));
```
이미지에 보이듯 토큰을 돌려주는 login이나 signup 요청의 tests 부분에 코드를 넣어줄 수 있습니다.
위와 같은 자바스크립트 코드를 넣어주시면 포스트맨이 토큰을 들고 있게 됩니다.

![image](https://github.com/yourweather/yourweather-server/assets/65557784/5d74bfd3-bb4c-443b-adda-c763799ba9a5)
> 토큰을 필요로 하는 home 요청
위의 이미지처럼 Authorization 버튼 -> Type 버튼을 누르면 여러 옵션이 나옵니다. 여기서 Bearer Token을 눌러주세요.

![image](https://github.com/yourweather/yourweather-server/assets/65557784/2f0d2c3d-e15a-41dc-97ba-5e47e194b2cc)
같은 화면에서 빨간 동그라미 쳐진 부분에 `{{access_token}}`을 넣어주시면 이 요청에 대해선 로그인, 회원가입만 잘 되어있어도 잘 작동할 것입니다.

이런 식으로 설정해주시고 요청 추가할 때마다 해주시면 아마도 단순 기능 테스트로는 테스트코드보다 이런 인수테스트가 속도는 더 빠를 거에요. 회귀 버그에 대해선 당연히 테스트 코드를 꽉꽉 채워주는 것이 안전하지만, 우리는 시간이 없으니까요..!

확인해보시고 혹시 토큰 설정이 어려우셨다면 이렇게 설정해서 진행해주세요!
