### ISSUE TITLE
memo/write 요청 폼 관련 제의

### ISSUE THREAD

**Issue by shon5544** [yourweather/yourweather-server#58]
## Description

![image](https://github.com/yourweather/yourweather-server/assets/65557784/ad24e93a-74a8-424e-8486-8869d589a237)
> /memo/write의 요청 body입니다.

여기서 연/월/일/시간/분/초 를 따로 받는데, 이렇게 모두 다 받는다면 프론트에서 LocalDateTime 필드 하나로 받는 게 좀 더 좋지 않을까 합니다..!

**Comment by HI-JIN2** [comment]
동의합니다. LocalDateTime 타입이 json에서 불가하다면, 저 형식 그대로 string으로 취급하는 것이 좋을 것 같습니다.
