### ISSUE TITLE
[FIX] write notes up to 10 times

### ISSUE THREAD

**Issue by shon5544** [yourweather/yourweather-server#87]
## Description

> 메모는 하루 당 최대 10번 쓰기로 했었습니다..! 현재 코드에 이 부분에 대한 내용이 없으니 추가해야합니다

## Progress

- [x] 메모 하루 당 최대 10번만 작성 가능
- [ ] 테스트

**Comment by HI-JIN2** [comment]
11번째 memo write에 대한 응답으로 400이랑 해당 상황에 대한 메시지를 반환하면 되는걸까요?

**Comment by packdev937** [comment]
MemoService()에 write와 관련해서 분기처리하면 될 것 같습니다. 
 if(memoRepository.findByUserAndWeatherId(user,weather).size() > 10){
            throw new RuntimeException("하루에 메모를 10개 이상 작성할 수 없습니다.");
        }

대충 이런식으로..? 근데 findByUserAndWeatherId인데 정작 require type은 Weather 객체네요..?

**Comment by shon5544** [comment]
> MemoService()에 write와 관련해서 분기처리하면 될 것 같습니다. if(memoRepository.findByUserAndWeatherId(user,weather).size() > 10){ throw new RuntimeException("하루에 메모를 10개 이상 작성할 수 없습니다."); }
> 
> 대충 이런식으로..? 근데 findByUserAndWeatherId인데 정작 require type은 Weather 객체네요..?

해당 메서드가 JPQL로 작성되어 메서드 네이밍은 기능에 영향을 미치진 않습니다만 제 생각에도 사용을 편하게 하려면 좀 더 직관적인 네이밍이 필요할 것 같습니다!
