### ISSUE TITLE
[FIX] add user condition for find no inputs

### ISSUE THREAD

**Issue by shon5544** [yourweather/yourweather-server#88]
## Description

> 미입력 날짜 조회 조건에 유저를 넣어야 합니다. 즉 검색 조건이 모든 유저를 대상으로 하는 것입니다. 현재 유저 조건이 없어 내가 08.11일에 입력을 했더라도 다른 유저가 입력을 안했으면 미입력 날짜로 취급될 겁니다.

## Progress

- [x] 미입력 날짜 조회에 유저 조건 추가
- [x] 테스트

**Comment by packdev937** [comment]
findWeatherByDateBetween에 User 객체 또한 파라미터로 넘겨주면 되지 않을까요?

**Comment by HI-JIN2** [comment]
> findWeatherByDateBetween에 User 객체 또한 파라미터로 넘겨주면 되지 않을까요?

맞아용 근데 메소드명에도 유저가 포함되어야하는지, 아니면 파라미터만 넘겨주면 되는지 궁금합니다 @shon5544

**Comment by shon5544** [comment]
> > findWeatherByDateBetween에 User 객체 또한 파라미터로 넘겨주면 되지 않을까요?
> 
> 맞아용 근데 메소드명에도 유저가 포함되어야하는지, 아니면 파라미터만 넘겨주면 되는지 궁금합니다 @shon5544
이 메서드 네이밍으로 개발을 한다면 메소드 명에 유저가 포함되어야 하죠! 이 메서드가 어떻게 생긴지는 봐야겠지만 JPQL로 작성되어있다면 쿼리에 user 조건만 추가해주면 될 것 같습니다!
